name: Auto Assign Issues to Project(s)

on:
  issues:
    types: [opened, labeled]
    
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign vendor issues to the Vendor project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: ${{ github.event.label.name == 'general member' || 'premier member' }}
      with:
        project: 'https://github.com/finopsfoundation/framework/projects/1'
        column_name: 'Backlog'
