name: Auto Assign Issues to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign vendor issues to the Vendor project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: contains(github.event.issue.labels.*.name == 'general member' || 'premier member')
      with:
        project: 'https://github.com/stevetrask/test/projects/1'
        column_name: 'Backlog'
